# Generated by Django 3.2.25 on 2024-08-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0194_auto_20240620_1404'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_categor_8de99d_idx',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='product_pro_slug_33a021_idx'),
        ),
    ]
