# Generated by Django 3.2.25 on 2024-08-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0043_merge_20240606_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='additional_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together=set(),
        ),
    ]
